### ISSUE TITLE
How to draw a polygon?

### ISSUE THREAD

**Issue by jmaguirrei** [FormidableLabs/victory-line#78]
Hello, if you try to draw a polygon, let's say a rectangle:

```
 <VictoryLine
    data={[
      {x: 0, y: 0},
      {x: 5, y: 0},
      {x: 5, y: 2},      
      {x: 0, y: 2}
    ]}
 />
```
(paste in)
http://victory.formidable.com/docs/victory-line

![victoryline](https://cloud.githubusercontent.com/assets/11958637/13443652/c0f4f00c-dfe0-11e5-9f0d-ab13c502dcb0.png)

It seems you can't "go back" in the X axis... But any SVG path allows you to move from point to point in any direction, right?

Thanks

**Comment by boygirl** [comment]
@jmaguirrei [VictoryArea](https://github.com/FormidableLabs/victory-chart/pull/103) is in a WIP PR, so that should be a big help. I'm going to close this issue, since this repo is deprecated. VictoryLine is now included in VictoryChart. If you feel that VictoryArea does not address your use case, please open a new issue on VictoryChart
